const SITE = {
  name: "A Mission For Life Foundation",
  tagline: "CARE. EMPOWER. TRANSFORM LIVES.",
  phoneTel: "+917610900038",
  phonePretty: "+91 76109 00038",
  wa: "917610900038",
};

const UI = {
  hi: {
    banner: "डेमो · तारीख, जगह, तस्वीरें और रील नमूना हैं। असली कैंप डिटेल मिलते ही यही कार्ड बदल जाएगा। Instagram पेज अभी बन रहा है।",
    hide: "छिपाएँ",
    feed: "अपडेट",
    camps: "कैंप",
    photos: "तस्वीरें",
    lede: "ब्लड डोनेशन कैंप की जानकारी, कहानियाँ, तस्वीरें और रील्स — एक ही फ़ीड में।",
    seeFeed: "फ़ीड देखें",
    whatsapp: "WhatsApp",
    call: "कॉल करें",
    upcoming: "आने वाला कैंप",
    viewCamp: "पूरी जानकारी",
    sample: "नमूना",
    story: "कहानी",
    reel: "रील",
    camp: "कैंप",
    photo: "तस्वीरें",
    contactTitle: "संपर्क",
    contactBody: "कैंप के बारे में पूछना हो तो कॉल या WhatsApp करें।",
    instaSoon: "Instagram जल्द आ रहा है",
    back: "फ़ीड पर वापस",
    attend: "मैं कैंप में आना चाहता हूँ",
    when: "समय",
    where: "जगह",
    by: "आयोजक",
    stepsTitle: "कैंप में क्या होगा",
    bringTitle: "साथ में लाइए",
    whoTitle: "कौन डोनेट कर सकता है",
    whoNote: "यह सामान्य जानकारी है। रक्तदान से पहले अंतिम फैसला कैंप की मेडिकल टीम करेगी।",
    reelTitle: "रील यहाँ चलेगी",
    reelBody: "Instagram या YouTube का लिंक जुड़ते ही यही रील यहीं खुलेगी। पेज अभी बन रहा है, इसलिए अभी लिंक नहीं है।",
    close: "बंद करें",
    photoNote: "कैंप की असली तस्वीरें बाद में यहाँ लगेंगी।",
    waText: "नमस्ते A Mission For Life Foundation, मुझे ब्लड डोनेशन कैंप के बारे में जानकारी चाहिए।",
    footer: "रक्तदान कैंप · कहानियाँ · तस्वीरें · रील्स",
    skip: "फ़ीड पर जाएँ",
    play: "रील देखें",
    mapNote: "पता तय होते ही नक्शा यहाँ खुलेगा।",
    langLabel: "भाषा",
  },
  en: {
    banner: "Demo · The date, venue, photos and reel are samples. They will be replaced when the real camp details arrive. The Instagram page is not live yet.",
    hide: "Hide",
    feed: "Feed",
    camps: "Camps",
    photos: "Photos",
    lede: "Blood donation camp details, stories, photos and reels — in one feed.",
    seeFeed: "View feed",
    whatsapp: "WhatsApp",
    call: "Call",
    upcoming: "Upcoming camp",
    viewCamp: "Full details",
    sample: "Sample",
    story: "Story",
    reel: "Reel",
    camp: "Camp",
    photo: "Photos",
    contactTitle: "Contact",
    contactBody: "Call or WhatsApp to ask about a camp.",
    instaSoon: "Instagram coming soon",
    back: "Back to feed",
    attend: "I want to attend",
    when: "Time",
    where: "Venue",
    by: "Organiser",
    stepsTitle: "What happens at the camp",
    bringTitle: "Please bring",
    whoTitle: "Who can donate",
    whoNote: "This is general information. The camp medical team makes the final decision before a donation.",
    reelTitle: "The reel will play here",
    reelBody: "When an Instagram or YouTube link is ready, the reel will open here. The page is not live yet, so there is no link today.",
    close: "Close",
    photoNote: "Real camp photos will be placed here afterwards.",
    waText: "Hello A Mission For Life Foundation, I would like details of the blood donation camp.",
    footer: "Blood donation camps · stories · photos · reels",
    skip: "Skip to feed",
    play: "Play reel",
    mapNote: "A map will appear here once the address is fixed.",
    langLabel: "Language",
  },
};

const POSTS = [
  {
    id: "sample-camp",
    type: "camp",
    sample: true,
    date: "2026-10-18",
    time: { hi: "सुबह 9:00 – दोपहर 2:00", en: "9:00 AM – 2:00 PM" },
    title: { hi: "ब्लड डोनेशन कैंप", en: "Blood Donation Camp" },
    place: { hi: "जगह जल्द घोषित होगी", en: "Venue to be announced" },
    body: {
      hi: "रजिस्ट्रेशन, स्वास्थ्य जाँच और रक्तदान एक ही जगह होगा। खाली पेट न आएँ। पहचान पत्र साथ रखें। कोई सवाल हो तो WhatsApp पर लिखें।",
      en: "Registration, a health check and donation happen in one place. Do not come on an empty stomach. Bring a photo ID. WhatsApp us if you have a question.",
    },
    steps: [
      { t: { hi: "रजिस्ट्रेशन", en: "Registration" }, d: { hi: "नाम और फोन नंबर लिखा जाएगा।", en: "Your name and phone number are noted." } },
      { t: { hi: "जाँच", en: "Health check" }, d: { hi: "मेडिकल टीम देखेगी कि रक्तदान सुरक्षित है।", en: "The medical team checks that a donation is safe." } },
      { t: { hi: "रक्तदान", en: "Donation" }, d: { hi: "टीम आपकी मदद करती रहेगी।", en: "The team stays with you through the donation." } },
      { t: { hi: "आराम", en: "Rest" }, d: { hi: "थोड़ी देर रुकें और पानी पिएँ।", en: "Rest for a while and have some water." } },
    ],
    bring: [
      { hi: "आधार कार्ड या कोई फोटो पहचान पत्र", en: "Aadhaar or another photo ID" },
      { hi: "कैंप से पहले हल्का भोजन और पानी", en: "A light meal and water before you arrive" },
      { hi: "थोड़ा अतिरिक्त समय — प्रक्रिया में देर लग सकती है", en: "A little extra time — the visit can take a while" },
    ],
    who: [
      { hi: "आमतौर पर 18 से 65 साल की उम्र", en: "Usually 18 to 65 years old" },
      { hi: "वजन लगभग 50 किलो या उससे अधिक", en: "Weight around 50 kg or more" },
      { hi: "उस दिन स्वस्थ महसूस हो रहा हो", en: "Feeling well on the day" },
      { hi: "हाल की बीमारी, नई दवा या टैटू हो तो टीम को बताएँ", en: "Tell the team about recent illness, new medicine or a tattoo" },
    ],
  },
  {
    id: "story-day",
    type: "story",
    sample: true,
    title: { hi: "कैंप वाले दिन की कहानी", en: "A camp-day story" },
    body: {
      hi: "सुबह रजिस्ट्रेशन डेस्क खुलेगा। स्वास्थ्य जाँच के बाद इच्छुक लोग रक्तदान के लिए आगे आएँगे। दिन के अंत में टीम सबका धन्यवाद लिखेगी। कैंप के बाद ऐसी ही कहानी, तस्वीरों के साथ, इस फ़ीड में लगेगी।",
      en: "The registration desk opens in the morning. After the health check, people who are ready come forward to donate. At the end of the day the team posts a thank-you. A story like this, with photos, will go on the feed after each camp.",
    },
  },
  {
    id: "sample-photos",
    type: "photos",
    sample: true,
    title: { hi: "कैंप की तस्वीरें", en: "Camp photos" },
    images: [
      { src: "assets/shot-1.svg", alt: { hi: "नमूना तस्वीर — कैंप", en: "Sample photo — camp" } },
      { src: "assets/shot-2.svg", alt: { hi: "नमूना तस्वीर — देखभाल", en: "Sample photo — care" } },
      { src: "assets/shot-3.svg", alt: { hi: "नमूना तस्वीर — साथ", en: "Sample photo — together" } },
    ],
  },
  {
    id: "sample-reel",
    type: "reel",
    sample: true,
    title: { hi: "कैंप रील", en: "Camp reel" },
    cover: "assets/reel.svg",
  },
  {
    id: "story-why",
    type: "story",
    sample: false,
    title: { hi: "हम क्यों हैं", en: "Why we are here" },
    body: {
      hi: "A Mission For Life Foundation का विश्वास देखभाल, सशक्त बनाना और जीवन बदलना है। रक्तदान कैंप की हर कहानी, तस्वीर और रील इसी पेज पर साझा होगी।",
      en: "A Mission For Life Foundation stands for care, empowerment and transforming lives. Every blood donation camp story, photo and reel will be shared on this page.",
    },
  },
];
